version: "3.8"

services:
  vault-server:
    network_mode: "host"
    image: vault:latest
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK
  mongo:
    network_mode: "host"
    image: mongo